services:

  caddy:
    platform: linux/arm64
    image: caddy:2
    restart: unless-stopped
    network_mode: host
    environment:
      PROD_DOMAIN: ${PROD_DOMAIN:-prod.example.org}
      DEV_DOMAIN: ${DEV_DOMAIN:-dev.example.org}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
